@echo off
chcp 65001 >nul
cd /d "%~dp0"
title Z80Z-chat

REM ============================================================
REM Z80Z-chat single-file installer (generated by build script)
REM First run = install wizard; later runs = launcher for start.js
REM NOTE: keep this shell section ASCII-only (Chinese REM lines
REM break cmd parsing under chcp 65001)
REM ============================================================

set "APP_VERSION=__APP_VERSION__"
REM build timestamp (injected by build script), shown as release time
set "APP_BUILT=__APP_BUILT__"
REM content fingerprint (sha256 of zip minus package.json, injected by build script)
REM used by smart update: identical fingerprint -> skip backup/npm install/build
set "PAYLOAD_SHA=__PAYLOAD_SHA__"
REM keep bootstrap files next to this bat (not %TEMP%: AV PDM flags it)
set "BS=%~dp0.z80z-chat-bootstrap.ps1"

REM ============================================================
REM Z80Z-chat preferences (auto-managed by the installer)
REM _CONFIG_HASH=nch1
REM _SKIP_UPDATE_PROMPT=false
REM _SKIP_UPDATE_PROMPT_VERSION=
REM _LAST_PROJECT=
REM PAD                                                                
REM ============================================================

REM parse preference block from this file itself
set "SKIP_UPDATE_PROMPT=0"
set "SKIP_UPDATE_PROMPT_VERSION="
set "LAST_PROJECT="
for /f "tokens=2 delims==" %%A in ('findstr /B /C:"REM _SKIP_UPDATE_PROMPT=" "%~f0"') do if "%%A"=="true" set "SKIP_UPDATE_PROMPT=1"
for /f "tokens=2 delims==" %%A in ('findstr /B /C:"REM _SKIP_UPDATE_PROMPT_VERSION=" "%~f0"') do set "SKIP_UPDATE_PROMPT_VERSION=%%A"
for /f "tokens=2 delims==" %%A in ('findstr /B /C:"REM _LAST_PROJECT=" "%~f0"') do set "LAST_PROJECT=%%A"

REM Locate embedded PS-base64 block via PowerShell and decode to ps1.
REM <nul: when stdin is redirected (automated runs), every child
REM process shares the same file handle; a preceding process would
REM advance the pointer to EOF and break Read-Host in the -File
REM stage below. NUL keeps this helper from touching the handle.
del /q "%BS%" >nul 2>nul
goto :RUN














__NODECHAT_PS_BEGIN__
# ============================================================
# Z80Z-chat single-file bootstrap (extracted by build script into
# a base64 block, decoded by certutil at runtime)
# Compatible with PowerShell 2.0+ / Windows 7+
# ============================================================
param(
  [string]$Root = '.',
  [string]$AppVersion = '0.0.0',
  [string]$AppBuilt = '',
  [string]$SkipUpdatePrompt = '0',
  [string]$SkipUpdatePromptVersion = '',
  [string]$LastProject = '',
  [string]$PayloadSha = ''
)

$ErrorActionPreference = 'Continue'
try { [Console]::OutputEncoding = [System.Text.Encoding]::UTF8 } catch {}

# 全局偏好（由 bat 自身配置区解析传入；修改会写回 bat）
$script:globalPrefs = @{
  skipUpdatePrompt = ($SkipUpdatePrompt -eq '1')
  skipUpdatePromptVersion = $SkipUpdatePromptVersion
  lastProject = $LastProject
}

# Remove quotes/whitespace possibly carried over from the cmd
# command line (trailing backslash + quote is parsed as a literal
# quote by PowerShell)
$Root = ([string]$Root).Trim().Trim('"')
$Root = [System.IO.Path]::GetFullPath($Root)
$BatFile = Join-Path $Root 'Z80Z-chat.bat'
$NodeDir = Join-Path $Root 'nodejs'
$NodeExe = Join-Path $NodeDir 'node.exe'
$BackupRoot = Join-Path $Root 'data-backup'
$ConfigFile = Join-Path $Root '.install-config.json'
$ScriptFile = Join-Path $Root '.z80z-chat-bootstrap.ps1'

# 正常退出时自删（防止中断/异常退出残留）；bat 提取前也会清理上次残留
function Self-Clean {
  Remove-Item $ScriptFile -Force -ErrorAction SilentlyContinue
}

# 检测系统 PATH 中的 Node.js（版本 >= 18 可用）
function Test-SystemNode {
  try {
    $v = (& node -v 2>$null | Out-String).Trim()
    if ($v -match '^v(\d+)\.') {
      $major = [int]$Matches[1]
      if ($major -ge 18) { return @{ ok = $true; version = $v } }
    }
  } catch {}
  return @{ ok = $false; version = '' }
}

# ---------- output helpers (VT-capable terminals get color) ----------
$ESC = [char]27
$supportsVT = $false
try { $supportsVT = [bool]$host.UI.SupportsVirtualTerminal } catch {}
# 重定向/管道输出时降级无色（PS 5.1 的 $host.UI 在重定向时仍可能报告支持 VT）
try { if ([Console]::IsOutputRedirected) { $supportsVT = $false } } catch {}

function Tone([string]$code, [string]$text) {
  if ($supportsVT) { Write-Host ($ESC + '[' + $code + 'm' + $text + $ESC + '[0m') } else { Write-Host $text }
}
function Ln([string]$t = '') { Write-Host $t }
# 每一步开始前清屏（与项目管理菜单一致，独占一屏）；
# 重定向/管道运行（自动化）时跳过，避免输出污染
function Clear-Screen {
  try { if ([Console]::IsOutputRedirected) { return } } catch {}
  try { Clear-Host } catch {}
}
function H1([string]$t) {
  Clear-Screen
  Ln ''
  Ln ('  ' + $t)
  Tone '38;5;69' ('  ' + ('─' * 48))
  Ln ''
}
function Item([int]$n, [string]$label) { Ln ('  ' + $n.ToString() + '.  ' + $label) }
function ItemWithDesc([int]$n, [string]$label, [string]$desc) {
  if ($desc -ne '') { Ln ('  ' + $n.ToString() + '.  ' + $label + ' ------ ' + $desc) }
  else { Ln ('  ' + $n.ToString() + '.  ' + $label) }
}
function Hint([string]$t) { Ln ('  ' + $t) }
function Ok([string]$t) { Tone '38;5;42' ('  ✔ ' + $t) }
function Bad([string]$t) { Tone '38;5;203' ('  ✖ ' + $t) }
function Warn([string]$t) { Tone '38;5;214' ('  ⚠ ' + $t) }
function Info([string]$t) { Tone '38;5;111' ('  ℹ ' + $t) }
function Prompt([string]$t) { Tone '38;5;220' ('  > ' + $t) }
function Progress([string]$t) { Tone '38;5;42' ('  ● ' + $t) }
function Separator {
  Tone '38;5;245' ('  ' + ('─' * 46))
}
function KeyValue([string]$key, [string]$value) {
  if ($supportsVT) {
    Tone '38;5;245' ('  ' + $key.PadRight(20) + ' : ')
    Tone '38;5;6' ('  ' + $value)
  } else {
    Ln ('  ' + $key.PadRight(20) + ' : ' + $value)
  }
}

# ---------- encoding-safe write (UTF-8 without BOM) ----------
function Write-Utf8([string]$path, [string]$content) {
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($path, $content, $enc)
}

# ---------- safely modify the preference block inside Z80Z-chat.bat ----------
# 只精确替换 `REM _KEY=VALUE` 行（不影响其他内容/行数），改前备份、失败恢复。
# bat 自身在 cmd 下可写（cmd 以共享模式打开脚本），修改从下次运行生效。
function Set-BatPreferenceSafe([string]$key, [string]$value) {
  try {
    $lines = [System.IO.File]::ReadAllLines($BatFile, [System.Text.Encoding]::UTF8)
    $hashOk = $false
    foreach ($l in $lines) {
      if ($l -match '^REM _CONFIG_HASH=([0-9a-z]+)$') {
        $hashOk = ($Matches[1] -eq 'nch1')
        break
      }
    }
    if (-not $hashOk) {
      Warn ('bat 配置区校验失败，跳过保存（' + $key + '）')
      return $false
    }
    $backup = $BatFile + '.prefs-bak'
    Copy-Item $BatFile $backup -Force -ErrorAction SilentlyContinue
    $found = $false
    $oldLen = 0
    $newLen = 0
    $newLines = @()
    foreach ($line in $lines) {
      if ($line -match ('^REM _' + $key + '=')) {
        $oldLen += $line.Length
        $repl = ('REM _' + $key + '=' + $value)
        $newLen += $repl.Length
        $newLines += $repl
        $found = $true
      } else {
        $newLines += $line
      }
    }
    if (-not $found) {
      Copy-Item $backup $BatFile -Force -ErrorAction SilentlyContinue
      Remove-Item $backup -Force -ErrorAction SilentlyContinue
      return $false
    }
    # 等长写入：调整 PAD 行（REM PAD + 空格）的填充长度，使写入前后
    # 文件总字节数保持不变。cmd 在 PS 退出后还会继续从旧 EOF 处读取
    # 本文件，文件一旦变长，残留字节就会被当作命令执行
    # （'"' is not recognized / exit 9009）
    $diff = $newLen - $oldLen
    for ($i = 0; $i -lt $newLines.Count; $i++) {
      if ($newLines[$i] -match '^REM PAD +$') {
        $pad = 64 - $diff
        if ($pad -lt 0) { $pad = 0 }
        $newLines[$i] = 'REM PAD' + (' ' * $pad)
        break
      }
    }
    # 末行不写换行（与构建产物一致）
    [System.IO.File]::WriteAllText($BatFile, ($newLines -join "`r`n"), (New-Object System.Text.UTF8Encoding($false)))
    Remove-Item $backup -Force -ErrorAction SilentlyContinue
    # 同步本次运行的内存偏好
    switch ($key) {
      'SKIP_UPDATE_PROMPT' { $script:globalPrefs['skipUpdatePrompt'] = ($value -eq 'true') }
      'SKIP_UPDATE_PROMPT_VERSION' { $script:globalPrefs['skipUpdatePromptVersion'] = $value }
      'LAST_PROJECT' { $script:globalPrefs['lastProject'] = $value }
    }
    return $true
  } catch {
    Bad ('保存 bat 偏好失败：' + $_.Exception.Message)
    if (Test-Path $backup) {
      Copy-Item $backup $BatFile -Force -ErrorAction SilentlyContinue
      Remove-Item $backup -Force -ErrorAction SilentlyContinue
    }
    return $false
  }
}

# ---------- JSON parsing (PS 2.0 fallback: JavaScriptSerializer) ----------
function ConvertFrom-JsonCompat([string]$s) {
  if ($PSVersionTable.PSVersion.Major -ge 3) { return ($s | ConvertFrom-Json) }
  Add-Type -AssemblyName System.Web.Extensions -ErrorAction SilentlyContinue
  $js = New-Object System.Web.Script.Serialization.JavaScriptSerializer
  return $js.DeserializeObject($s)
}

# ---------- unified JSON field access (PSCustomObject vs Hashtable) ----------
function Get-JsonValue($obj, [string]$key) {
  if ($obj -eq $null) { return $null }
  if ($obj -is [System.Collections.IDictionary]) { return $obj[$key] }
  $p = $obj.PSObject.Properties[$key]
  if ($p) { return $p.Value }
  return $null
}

# ---------- extract embedded block from Z80Z-chat.bat ----------
function Extract-Block([string]$begin, [string]$end) {
  $lines = [System.IO.File]::ReadAllLines($BatFile, [System.Text.Encoding]::UTF8)
  $b = [Array]::IndexOf($lines, $begin)
  $e = [Array]::IndexOf($lines, $end)
  if ($b -lt 0 -or $e -lt 0 -or $e -lt $b) { throw ('内嵌块缺失: ' + $begin) }
  return ,@($lines[($b + 1)..($e - 1)])
}

# ---------- config: defaults + (legacy) outer .install-config.json + project config.json ----------
function Read-Config([string]$projDir = '') {
  $def = @{
    backupKeep = 3
    nodeVersion = '22'
    nodeMirror = ''
    npmRegistry = ''
  }
  # 兼容旧版：外层 .install-config.json 存在时并入（安装/更新完成后会删除）
  if (Test-Path $ConfigFile) {
    try {
      $c = ConvertFrom-JsonCompat ([System.IO.File]::ReadAllText($ConfigFile, [System.Text.Encoding]::UTF8))
      foreach ($k in @($def.Keys)) {
        $v = Get-JsonValue $c $k
        if ($v -ne $null -and "$v" -ne '') { $def[$k] = $v }
      }
    } catch {}
  }
  # 项目内 config.json 优先（方案：安装后外层配置删除，字段由 config.json 承载）
  if ($projDir -ne '' -and (Test-Path (Join-Path $projDir 'config.json'))) {
    try {
      $clean = Strip-Comments ([System.IO.File]::ReadAllText((Join-Path $projDir 'config.json'), [System.Text.Encoding]::UTF8))
      $j = ConvertFrom-JsonCompat $clean
      foreach ($k in @($def.Keys)) {
        $v = Get-JsonValue $j $k
        if ($v -ne $null -and "$v" -ne '') { $def[$k] = $v }
      }
    } catch {}
  }
  try { $def['backupKeep'] = [int]$def['backupKeep'] } catch { $def['backupKeep'] = 3 }
  return $def
}

# 把镜像线路写进项目 config.json（去重替换：所有同名键合并为一个，保留注释）
# 历史 bug 修复：旧实现用「替换结果是否变化」判断是否匹配，当新值等于现值时
# 结果不变导致误判为未匹配、每次运行都在文件尾追加一组重复键（npmRegistry/nodeMirror 三连）。
# 现在按匹配计数处理：第一个匹配更新值，后续重复键（连同前导逗号）删除，零匹配才追加。
function Set-ConfigField([string]$projDir, [string]$key, [string]$value) {
  $path = Join-Path $projDir 'config.json'
  if (-not (Test-Path $path)) { return }
  $raw = [System.IO.File]::ReadAllText($path, [System.Text.Encoding]::UTF8)
  $esc = $value.Replace('\', '\\').Replace('"', '\"')
  $pattern = (',?"' + $key + '":\s*"[^"]*"')
  $state = @{ n = 0 }
  $new = [System.Text.RegularExpressions.Regex]::Replace($raw, $pattern, {
    param($m)
    $state.n++
    if ($state.n -eq 1) {
      return ($m.Value -replace ('"' + $key + '":\s*"[^"]*"'), ('"' + $key + '": "' + $esc + '"'))
    }
    return ''
  })
  if ($state.n -eq 0) {
    $trimmed = $raw.TrimEnd()
    if ($trimmed.EndsWith('}')) {
      $new = $trimmed.Substring(0, $trimmed.Length - 1).TrimEnd() + (',"' + $key + '": "' + $esc + '"}')
    }
  }
  if ($new -ne $raw) { Write-Utf8 $path $new }
}

# ---------- network lines (Node.js mirror + npm registry paired) ----------
$LINES = @(
  @{ name = 'npm 官方';         node = 'https://nodejs.org/dist';                    npm = 'https://registry.npmjs.org/' },
  @{ name = 'npmmirror (阿里)'; node = 'https://npmmirror.com/mirrors/node';         npm = 'https://registry.npmmirror.com' },
  @{ name = '华为云';            node = 'https://repo.huaweicloud.com/nodejs';         npm = 'https://repo.huaweicloud.com/repository/npm/' },
  @{ name = '腾讯云';            node = 'https://mirrors.cloud.tencent.com/nodejs';    npm = 'https://mirrors.cloud.tencent.com/npm/' },
  @{ name = '中科大';            node = 'https://mirrors.ustc.edu.cn/nodejs-release';  npm = 'https://mirrors.ustc.edu.cn/npm/' }
)

function Test-Lines {
  try { [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12 } catch {}
  $results = @()
  foreach ($line in $LINES) {
    $ms = 99999
    # 测速目标：index.json（各镜像根目录均存在，HEAD 稳定可达）。
    # 注意：不能用 /v22/SHASUMS256.txt（该路径不存在，SHASUMS 只在具体版本目录里，会全部 404 误判失败）
    $testUrl = $line['node'] + '/index.json'
    for ($try = 0; $try -lt 2 -and $ms -eq 99999; $try++) {
      try {
        $req = [System.Net.HttpWebRequest]::Create($testUrl)
        $req.Method = 'HEAD'
        $req.Timeout = 8000
        $req.Proxy = $null
        $sw = [System.Diagnostics.Stopwatch]::StartNew()
        $resp = $req.GetResponse()
        $sw.Stop()
        $ms = $sw.ElapsedMilliseconds
        $resp.Close()
      } catch { $ms = 99999 }
    }
    $r = @{ name = $line['name']; node = $line['node']; npm = $line['npm']; ms = $ms }
    $results += $r
  }
  # hashtable 无 'ms' 属性，Sort-Object 必须用脚本块表达式访问 key
  return ($results | Sort-Object @{ Expression = { $_['ms'] }; Ascending = $true })
}

function Choose-Line([string]$purpose) {
  H1 '网络线路选择'
  Info ('当前准备下载：' + $purpose)
  Ln ''
  Ln '  正在测速（延迟越低越好）...'
  Ln ''
  $lines = Test-Lines
  # 全线路不可达时明确提示（网络/代理/防火墙问题），不进入选择
  $reachable = @($lines | Where-Object { $_['ms'] -lt 99999 })
  if ($reachable.Count -eq 0) {
    Warn '所有线路测速均失败：请检查网络连接，或关闭代理软件（v2ray/Clash 等）的系统代理后重试'
    Ln ''
    Separator
    Ln ''
    Read-Host '  按回车重新测速'
    return $null
  }
  $i = 1
  foreach ($l in $lines) {
    $t = '超时'
    $colorCode = '38;5;203'
    if ($l['ms'] -lt 99999) {
      $t = ($l['ms'].ToString() + ' ms')
      if ($l['ms'] -lt 50) { $colorCode = '38;5;42' }
      elseif ($l['ms'] -lt 150) { $colorCode = '38;5;220' }
      else { $colorCode = '38;5;214' }
    }
    Tone '38;5;111' ('  ' + $i.ToString() + '.  ' + ($l['name']).PadRight(16))
    Tone $colorCode ('      延迟：' + $t)
    $i++
  }
  Ln ''
  Separator
  Ln ''
  $ch = (Read-Host '  选择线路编号（留空自动选最快）').Trim()
  $idx = 0
  if ($ch -ne '') {
    $n = 0
    try { $n = [int]$ch } catch { $n = 0 }
    if ($n -ge 1 -and $n -le $lines.Count) { $idx = $n - 1 }
  }
  $sel = $lines[$idx]
  Ln ''
  Ok ('已选择线路：' + $sel['name'])
  return $sel
}

# ---------- latest Node.js version for the configured major ----------
# 注意：WebClient 没有 Timeout 属性（设置会抛异常），失败时返回 $null 由调用方处理
function Get-NodeVersion([string]$mirror, [string]$major) {
  try {
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12
  } catch {}
  try {
    $wc = New-Object System.Net.WebClient
    $wc.Proxy = $null
    $txt = $wc.DownloadString($mirror + '/index.json')
    $list = ConvertFrom-JsonCompat $txt
    foreach ($item in $list) {
      $v = Get-JsonValue $item 'version'
      if ($v -like ('v' + $major + '.*')) {
        # index.json 的 version 带 v 前缀（如 "v22.23.2"），返回裸版本号，
        # 调用方拼接 '/v' + $ver 才不会变成 '/vv22.23.2/'（404）
        return ($v -replace '^v', '')
      }
    }
  } catch {}
  return $null
}

# ---------- SHA256 ----------
function Get-Sha256([string]$path) {
  $sha = [System.Security.Cryptography.SHA256]::Create()
  $fs = [System.IO.File]::OpenRead($path)
  try { $hash = $sha.ComputeHash($fs) } finally { $fs.Close() }
  $sb = New-Object System.Text.StringBuilder
  foreach ($b in $hash) { [void]$sb.Append($b.ToString('x2')) }
  return $sb.ToString()
}

# ---------- download (no proxy, TLS1.2, timeout via HttpWebRequest) ----------
function Download-File([string]$url, [string]$dest) {
  # 绕过系统代理（WebClient 默认继承 IE 代理设置，用户开代理软件时会导致全线下载失败）
  # 显式 TLS 1.2（PS 5.1 SystemDefault 可能回退到 TLS1.0 被服务器拒绝）
  # 用 HttpWebRequest + 流式写出：支持超时（WebClient.DownloadFile 无法设置超时，可能无限挂起）
  try { [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Net.SecurityProtocolType]::Tls12 } catch {}
  $req = [System.Net.HttpWebRequest]::Create($url)
  $req.Method = 'GET'
  $req.Timeout = 120000
  $req.ReadWriteTimeout = 120000
  $req.Proxy = $null
  $resp = $req.GetResponse()
  try {
    $in = $resp.GetResponseStream()
    $out = [System.IO.File]::Create($dest)
    try {
      $buf = New-Object byte[] 65536
      while (($read = $in.Read($buf, 0, $buf.Length)) -gt 0) {
        $out.Write($buf, 0, $read)
      }
    } finally { $out.Close() }
  } finally { $resp.Close() }
}

# ---------- unzip (Expand-Archive fallback for PS 3+) ----------
function Expand-Zip([string]$zip, [string]$dest) {
  try {
    Add-Type -AssemblyName System.IO.Compression.FileSystem -ErrorAction Stop
    [System.IO.Compression.ZipFile]::ExtractToDirectory($zip, $dest)
  } catch {
    Expand-Archive -Path $zip -DestinationPath $dest -Force
  }
}

# ---------- manual download tutorial ----------
function Show-ManualTutorial {
  H1 '手动下载教程'
  Info '步骤 1：下载与你系统对应的版本的 Node.js'
  Ln ''
  Hint '  下载源：'
  Ln ''
  Ln '    官方源：https://nodejs.org/'
  Ln '    npmmirror：https://npmmirror.com/mirrors/node/'
  Ln '    华为云：https://repo.huaweicloud.com/nodejs/'
  Ln '    腾讯云：https://mirrors.cloud.tencent.com/nodejs/'
  Ln ''
  Separator
  Ln ''
  Info '步骤 2：解压 zip 压缩包'
  Ln ''
  Hint '  Windows 请选择“Windows Binary (.zip)”，并使用解压软件解压，64 位选 win-x64'
  Ln ''
  Separator
  Ln ''
  Info '步骤 3：放入目录'
  Ln ''
  Hint '  将 node.exe、npm.cmd 所在目录的内容'
  Hint '  放入当前文件夹内的 nodejs/ 目录'
  Ln ''
  Separator
  Ln ''
  Read-Host '  按回车返回上一级'
}

# ---------- install Node.js (explanation text below the options) ----------
function Ensure-NodeJs($cfg) {
  if (Test-Path $NodeExe) { return $true }
  # 系统 Node.js 检测（仅询问一次）
  if (-not $script:sysNodeChecked) {
    $script:sysNodeChecked = $true
    $sys = Test-SystemNode
    if ($sys['ok']) {
      H1 'Node.js 运行环境'
      Ln ''
      Info '本目录下未找到 nodejs/ 文件夹，'
      Info ('但检测到系统拥有 Node.js ' + $sys['version'])
      Ln ''
      ItemWithDesc 1 '使用系统 Node.js' '不下载，直接使用系统环境'
      ItemWithDesc 2 '下载 nodejs/' '推荐，环境隔离，不影响系统'
      ItemWithDesc 3 '退出' '稍后手动安装'
      Ln ''
      Separator
      Ln ''
      $ch2 = (Read-Host '  输入选项编号').Trim()
      if ($ch2 -eq '1') {
        $script:useSystemNode = $true
        Ok ('将使用系统 Node.js ' + $sys['version'])
        Ln ''
        return $true
      }
      if ($ch2 -eq '3') { Self-Clean; exit 0 }
    }
  }
  H1 '需要下载 Node.js 并安装'
  Ln ''
  Warn '未检测到 Node.js 运行环境'
  Ln ''
  ItemWithDesc 1 '自动下载 Node.js 安装（约 25MB）' '推荐，一键安装'
  ItemWithDesc 2 '手动下载（内含教程）' '手动下载后放入 nodejs/ 目录'
  ItemWithDesc 3 '退出' '稍后手动安装'
  Ln ''
  Separator
  Ln ''
  Ln '  为什么需要 Node.js？'
  Ln ''
  Hint '  本项目是 Node.js 应用，运行时必须有 Node.js 环境，'
  Hint '  类似浏览器运行网页需要 Chrome。'
  Hint '  它用于：运行后端服务、安装依赖（npm）、构建前端。'
  Hint '  Node.js 将安装到当前文件夹内的 nodejs/ 目录，'
  Hint '  不影响系统其他程序。'
  Ln ''
  Separator
  Ln ''
  $ch = (Read-Host '  输入选项编号').Trim()
  if ($ch -eq '2') {
    Show-ManualTutorial
    return $false
  }
  if ($ch -ne '1') { Self-Clean; exit 0 }

  $script:selLine = Choose-Line ('Node.js 运行时（约 25MB）')
  if ($null -eq $script:selLine) { return $false }

  $ver = Get-NodeVersion $script:selLine['node'] $cfg['nodeVersion']
  if ($null -eq $ver) {
    Bad ('无法从 ' + $script:selLine['name'] + ' 获取 Node.js 版本列表（index.json 下载失败）')
    Hint '  若你开启了代理软件（v2ray/Clash 等），请先关闭「系统代理」再重试'
    Ln ''
    Separator
    Ln ''
    Read-Host '  按回车重新选择线路下载'
    return $false
  }
  $arch = $env:PROCESSOR_ARCHITECTURE
  $osName = 'win-x64'
  if ($arch -eq 'ARM64') { $osName = 'win-arm64' }
  $file = 'node-' + $ver + '-' + $osName + '.zip'
  $zipUrl = $script:selLine['node'] + '/v' + $ver + '/' + $file
  $zip = Join-Path $Root $file
  $shasumsUrl = $script:selLine['node'] + '/v' + $ver + '/SHASUMS256.txt'
  $shasums = Join-Path $Root '.node-shasums.txt'
  Ln ''
  Progress ('正在下载 ' + $file + '（' + $script:selLine['name'] + '，网络较慢时可能需要数分钟）...')
  Ln ''
  try {
    Hint '  下载 SHA256 校验文件...'
    try {
      # 小文件同样可能因网络波动失败：重试 2 次
      $shasumsOk = $false
      for ($attempt = 1; $attempt -le 2 -and -not $shasumsOk; $attempt++) {
        try {
          Download-File $shasumsUrl $shasums
          $shasumsOk = $true
        } catch {
          Remove-Item $shasums -Force -ErrorAction SilentlyContinue
          if ($attempt -lt 2) { Start-Sleep -Seconds 1 }
        }
      }
      if (-not $shasumsOk) { throw 'shasums 下载失败' }
    } catch {
      # 404（该镜像此版本未同步）与网络中断是不同问题，给出明确指引
      if ($_.Exception.Message -match '404|(The remote server returned an error)') {
        Bad ('该镜像（' + $script:selLine['name'] + '）可能尚未同步此版本（' + $ver + '），换一条线路重试')
      } else {
        Bad ('SHA256 校验文件下载失败：' + $_.Exception.Message)
        Hint '  若你开启了代理软件（v2ray/Clash 等），请先关闭「系统代理」再重试'
      }
      Remove-Item $shasums -Force -ErrorAction SilentlyContinue
      Separator
      Ln ''
      Read-Host '  按回车重新选择线路下载'
      return $false
    }
    Hint '  下载 Node.js...'
    # zip 较大（约 35MB），网络波动可能中途断连：自动重试最多 3 次
    $zipOk = $false
    for ($attempt = 1; $attempt -le 3 -and -not $zipOk; $attempt++) {
      try {
        Download-File $zipUrl $zip
        $zipOk = $true
      } catch {
        Remove-Item $zip -Force -ErrorAction SilentlyContinue
        if ($attempt -lt 3) {
          Hint ('  下载中断（第 ' + $attempt + ' 次），2 秒后自动重试...')
          Start-Sleep -Seconds 2
        }
      }
    }
    if (-not $zipOk) { throw 'zip 下载失败（已重试 3 次）' }
  } catch {
    Bad 'Node.js 压缩包下载失败（网络中断或代理异常）'
    Hint '  若你开启了代理软件（v2ray/Clash 等），请先关闭「系统代理」再重试'
    Remove-Item $zip -Force -ErrorAction SilentlyContinue
    Remove-Item $shasums -Force -ErrorAction SilentlyContinue
    Separator
    Ln ''
    Read-Host '  按回车重新选择线路下载'
    return $false
  }
  Ln ''
  Progress '校验文件完整性（SHA256）...'
  $actual = Get-Sha256 $zip
  $expected = ''
  if (Test-Path $shasums) {
    foreach ($l in [System.IO.File]::ReadAllLines($shasums, [System.Text.Encoding]::UTF8)) {
      $p = $l.Trim()
      if ($p.EndsWith($file)) { $expected = ($p -split '\s+')[0]; break }
    }
  }
  if ($expected -eq '' -or $actual -ne $expected) {
    Bad 'SHA256 校验失败（下载不完整或被篡改），已删除损坏文件，请稍后重试'
    Remove-Item $zip -Force -ErrorAction SilentlyContinue
    Remove-Item $shasums -Force -ErrorAction SilentlyContinue
    Separator
    Ln ''
    Read-Host '  按回车重新选择线路下载'
    return $false
  }
  Ok 'SHA256 校验通过'
  Ln ''
  Progress '解压中...'
  $tmp = Join-Path $Root ('nodejs-tmp-' + [System.Guid]::NewGuid().ToString('N'))
  try {
    Expand-Zip $zip $tmp
    $sub = Get-ChildItem $tmp | Where-Object { $_.PSIsContainer } | Select-Object -First 1
    New-Item -ItemType Directory -Path $NodeDir -Force | Out-Null
    if ($sub) {
      Get-ChildItem $sub.FullName | Copy-Item -Destination $NodeDir -Recurse -Force
    } else {
      Get-ChildItem $tmp | Copy-Item -Destination $NodeDir -Recurse -Force
    }
    Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
  } catch {
    Bad ('解压失败：' + $_.Exception.Message)
    Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
    Separator
    Ln ''
    Read-Host '  按回车返回'
    return $false
  }
  Remove-Item $zip -Force -ErrorAction SilentlyContinue
  Remove-Item $shasums -Force -ErrorAction SilentlyContinue
  Ok 'Node.js 安装完成'
  Ln ''
  Info ('安装位置：' + $NodeDir)
  Ln ''
  Hint 'Node.js 与项目本体在同一文件夹内（nodejs/），卸载时'
  Hint '删除整个文件夹即可彻底卸载。'
  Ln ''
  Read-Host '  按回车开始下一步'
  return $true
}

# ---------- stop running service (PID file first, port fallback) ----------
# strip JSON comments (// and /* */, strings untouched), same as config/index.js
function Strip-Comments([string]$src) {
  $out = New-Object System.Text.StringBuilder
  $inStr = $false
  $inLine = $false
  $inBlock = $false
  for ($i = 0; $i -lt $src.Length; $i++) {
    $c = $src[$i]
    $nxt = ''
    if ($i + 1 -lt $src.Length) { $nxt = $src[$i + 1] }
    if ($inLine) {
      if ($c -eq "`n") { $inLine = $false; [void]$out.Append($c) }
      continue
    }
    if ($inBlock) {
      if ($c -eq '*' -and $nxt -eq '/') { $inBlock = $false; $i++ }
      continue
    }
    if ($inStr) {
      [void]$out.Append($c)
      if ($c -eq '\') { if ($nxt -ne '') { [void]$out.Append($nxt); $i++ } }
      elseif ($c -eq '"') { $inStr = $false }
      continue
    }
    if ($c -eq '"') { $inStr = $true; [void]$out.Append($c); continue }
    if ($c -eq '/' -and $nxt -eq '/') { $inLine = $true; $i++; continue }
    if ($c -eq '/' -and $nxt -eq '*') { $inBlock = $true; $i++; continue }
    [void]$out.Append($c)
  }
  return $out.ToString()
}

function Get-PortFromConfig($projDir) {
  $cfg = Join-Path $projDir 'config.json'
  if (-not (Test-Path $cfg)) { return $null }
  try {
    $clean = Strip-Comments ([System.IO.File]::ReadAllText($cfg, [System.Text.Encoding]::UTF8))
    $j = ConvertFrom-JsonCompat $clean
    return (Get-JsonValue $j 'port')
  } catch { return $null }
}

function Stop-Service($projDir) {
  Ln '  停止服务中...'
  $stopped = $false
  $pidFile = Join-Path $projDir 'data\server.pid'
  if (Test-Path $pidFile) {
    try {
      $p = ([System.IO.File]::ReadAllText($pidFile, [System.Text.Encoding]::UTF8)).Trim()
      if ($p -match '^\d+$') {
        Stop-Process -Id ([int]$p) -Force -ErrorAction SilentlyContinue
        $stopped = $true
      }
    } catch {}
    Remove-Item $pidFile -Force -ErrorAction SilentlyContinue
  }
  $port = Get-PortFromConfig $projDir
  if ($port) {
    try {
      $out = (& netstat -ano -p tcp 2>$null) -match 'LISTENING' -match (':' + $port + ' ')
      foreach ($line in $out) {
        if ($line -match '(\d+)\s*$') {
          $pid = [int]$Matches[1]
          if ($pid -gt 0) { Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue; $stopped = $true }
        }
      }
    } catch {}
  }
  if ($stopped) { Ok '服务已停止' } else { Ln '  未检测到运行中的服务' }
  Start-Sleep -Milliseconds 500
}

# ---------- random available port (10000-60000) ----------
function Get-RandomAvailablePort {
  for ($i = 0; $i -lt 100; $i++) {
    $p = Get-Random -Minimum 10000 -Maximum 60001
    $inUse = $false
    try {
      $out = (netstat -ano -p tcp 2>$null) -match 'LISTENING' -match (':' + $p + ' ')
      if ($out) { $inUse = $true }
    } catch {}
    if (-not $inUse) { return $p }
  }
  return 3000
}

# ---------- ask port and update project config.json (keep comments) ----------
function Ask-Port($projDir) {
  $projConfig = Join-Path $projDir 'config.json'
  $current = 3000
  if (Test-Path $projConfig) {
    try {
      $clean = Strip-Comments ([System.IO.File]::ReadAllText($projConfig, [System.Text.Encoding]::UTF8))
      $j = ConvertFrom-JsonCompat $clean
      $v = Get-JsonValue $j 'port'
      if ($v -ne $null) { $current = [int]$v }
    } catch {}
  }
  H1 '端口配置'
  Ln ''
  Hint '  端口范围：1-65535'
  Hint '  常用端口：80、443、8080'
  Hint '  留空：自动选择随机端口（10000-60000）'
  Ln ''
  $input = (Read-Host '  请输入端口号（留空自动选择随机端口 10000-60000）').Trim()
  $port = 0
  if ($input -eq '') {
    $port = Get-RandomAvailablePort
    Ln ''
    Ok ('已自动选择端口：' + $port)
  } else {
    try { $port = [int]$input } catch { $port = 0 }
    if ($port -lt 1 -or $port -gt 65535) {
      Bad '端口号无效（应为 1-65535 的整数），保持当前端口不变'
      return
    }
  }
  if ($port -ne $current) {
    $raw = [System.IO.File]::ReadAllText($projConfig, [System.Text.Encoding]::UTF8)
    $raw = [System.Text.RegularExpressions.Regex]::Replace($raw, '"port":\s*\d+', ('"port": ' + $port))
    Write-Utf8 $projConfig $raw
    Ok ('config.json 端口已更新为 ' + $port)
  }
}

# ---------- backup data to data-backup\backup-<stamp> (keep backupKeep) ----------
function Backup-Data($projDir, $cfg) {
  $data = Join-Path $projDir 'data'
  if (-not (Test-Path $data)) {
    Info '无 data 目录，跳过备份'
    return
  }
  $stamp = Get-Date -Format 'yyyyMMdd-HHmmssfff'
  $dest = Join-Path $BackupRoot ('backup-' + $stamp)
  New-Item -ItemType Directory -Path $dest -Force | Out-Null
  Get-ChildItem $data | Copy-Item -Destination $dest -Recurse -Force
  Ok ('已备份数据 → ' + $dest)
  $keep = 3
  try { $keep = [int]$cfg['backupKeep'] } catch {}
  if ($keep -lt 1) { $keep = 1 }
  $all = Get-ChildItem $BackupRoot | Where-Object { $_.PSIsContainer } | Sort-Object Name
  $excess = $all.Count - $keep
  if ($excess -gt 0) {
    $all | Select-Object -First $excess | ForEach-Object {
      Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue
    }
    Hint ('已清理旧备份 ' + $excess + ' 份（保留 ' + $keep + ' 份，可在 config.json 修改）')
  }
}

# ---------- rebuild project (keep data / logs / node_modules / config.json) ----------
function Rebuild-Project($projDir) {
  Progress '重建项目文件（保留 data / logs / node_modules / config.json）...'
  $keepNames = @('data', 'logs', 'node_modules', 'config.json')
  Get-ChildItem $projDir -Force | Where-Object { $keepNames -notcontains $_.Name } | ForEach-Object {
    Remove-Item $_.FullName -Recurse -Force -ErrorAction SilentlyContinue
  }
}

# ---------- release project files (extract start.js + restore zip) ----------
function Write-Project($projDir, [bool]$keepConfig = $false) {
  $cfgPath = Join-Path $projDir 'config.json'
  $holdCfg = ''
  # 更新场景：解压前移走用户版 config.json，解压后移回（zip 默认版会被覆盖丢弃）
  if ($keepConfig -and (Test-Path $cfgPath)) {
    $holdCfg = Join-Path $projDir ('.config.' + [System.Guid]::NewGuid().ToString('N'))
    Move-Item $cfgPath $holdCfg -Force
  }
  $js = Extract-Block '__NODECHAT_STARTJS_BEGIN__' '__NODECHAT_STARTJS_END__'
  Write-Utf8 (Join-Path $projDir 'start.js') ($js -join "`n")
  $b64 = Extract-Block '__NODECHAT_ZIP_B64_BEGIN__' '__NODECHAT_ZIP_B64_END__'
  $bytes = [System.Convert]::FromBase64String(($b64 -join ''))
  $zip = Join-Path $projDir '.project.zip'
  [System.IO.File]::WriteAllBytes($zip, $bytes)
  try {
    Expand-Zip $zip $projDir
  } finally {
    Remove-Item $zip -Force -ErrorAction SilentlyContinue
  }
  if ($holdCfg -ne '') {
    Move-Item $holdCfg $cfgPath -Force
  }
}

# ---------- npm install / build (system node or bundled nodejs) ----------
function Invoke-NpmInstall($projDir, $cfg) {
  $registry = $cfg['npmRegistry']
  if ($registry -eq '') { $registry = 'https://registry.npmmirror.com' }
  Push-Location $projDir
  try {
    Progress '安装依赖（npm install，可能需要几分钟）...'
    if ($script:useSystemNode) {
      cmd /c ('npm install --registry=' + $registry)
    } else {
      $npm = Join-Path $NodeDir 'npm.cmd'
      if (Test-Path $npm) {
        cmd /c ('"' + $npm + '" install --registry=' + $registry)
      } else {
        & $NodeExe (Join-Path $NodeDir 'node_modules\npm\bin\npm-cli.js') install '--registry=' + $registry
      }
    }
    if ($LASTEXITCODE -ne 0) { throw 'npm install 失败（退出码 ' + $LASTEXITCODE + '）' }
  } finally { Pop-Location }
}

function Invoke-NpmBuild($projDir) {
  Push-Location $projDir
  try {
    Progress '构建前端（npm run build）...'
    if ($script:useSystemNode) {
      cmd /c 'npm run build'
    } else {
      $npm = Join-Path $NodeDir 'npm.cmd'
      if (Test-Path $npm) {
        cmd /c ('"' + $npm + '" run build')
      } else {
        & $NodeExe (Join-Path $NodeDir 'node_modules\npm\bin\npm-cli.js') run build
      }
    }
    if ($LASTEXITCODE -ne 0) { throw '前端构建失败（退出码 ' + $LASTEXITCODE + '）' }
  } finally { Pop-Location }
}

# ---------- content fingerprint: sha256 of all files except package.json (matches build script) ----------
function Compute-PayloadSha([string]$dir) {
  $rels = @()
  foreach ($f in (Get-ChildItem $dir -Recurse -Force -ErrorAction SilentlyContinue)) {
    if ($f.PSIsContainer) { continue }
    if ($f.Name -eq 'package.json') { continue }
    $rels += $f.FullName.Substring($dir.Length).TrimStart('\').Replace('\', '/')
  }
  [Array]::Sort($rels, [System.StringComparer]::Ordinal)
  $ms = New-Object System.IO.MemoryStream
  $sha = [System.Security.Cryptography.SHA256]::Create()
  foreach ($rel in $rels) {
    $bytes = [System.IO.File]::ReadAllBytes((Join-Path $dir ($rel.Replace('/', '\'))))
    $sb = [System.Text.Encoding]::UTF8.GetBytes($rel)
    $ms.Write($sb, 0, $sb.Length)
    $ms.WriteByte(0)
    $hb = $sha.ComputeHash($bytes)
    $ms.Write($hb, 0, $hb.Length)
  }
  $h = $sha.ComputeHash($ms.ToArray())
  $hex = ''
  foreach ($b in $h) { $hex += $b.ToString('x2') }
  return $hex
}

# ---------- dependency fingerprint: sorted "deps:@version" entries (excludes package.json version field) ----------
function Get-DepsKey([string]$pkgPath) {
  if (-not (Test-Path $pkgPath)) { return '' }
  try {
    $pkg = ConvertFrom-JsonCompat ([System.IO.File]::ReadAllText($pkgPath, [System.Text.Encoding]::UTF8))
    $list = New-Object System.Collections.ArrayList
    foreach ($sec in @('dependencies', 'devDependencies')) {
      $d = Get-JsonValue $pkg $sec
      if ($d -eq $null) { continue }
      if ($d -is [System.Collections.IDictionary]) {
        $names = @($d.Keys)
      } else {
        $names = @($d.PSObject.Properties | ForEach-Object { $_.Name })
      }
      foreach ($n in $names) {
        $v = Get-JsonValue $d $n
        $null = $list.Add($sec + ':' + $n + '@' + $v)
      }
    }
    $arr = @($list.ToArray())
    [Array]::Sort($arr, [System.StringComparer]::Ordinal)
    return ($arr -join '|')
  } catch { return '' }
}

function Write-VersionMarker($projDir, [string]$payloadHash = '') {
  $mv = '{"version": "' + $AppVersion + '", "installedAt": "' + (Get-Date -Format 'yyyy-MM-ddTHH:mm:ss') + '"'
  if ($payloadHash -ne '') { $mv += ', "payloadHash": "' + $payloadHash + '"' }
  $mv += '}'
  Write-Utf8 (Join-Path $projDir '.install-version') $mv
}

# ---------- run management menu ----------
function Run($projDir, [bool]$directUse = $false) {
  # 本地 nodejs/ 缺失时自动回退系统 node（与首次安装的选择保持一致，
  # 无需持久化：下载过 nodejs 则本地存在；选过系统 node 则本地缺失）
  if (-not $script:useSystemNode -and -not (Test-Path $NodeExe)) {
    $sys = Test-SystemNode
    if ($sys['ok']) { $script:useSystemNode = $true }
  }
  # "直接使用现有目录"进入：通知 start.js 跳过第一次安装建议
  $args2 = @('start.js')
  if ($directUse) { $args2 += '--direct-use' }
  if ($script:useSystemNode) {
    Push-Location $projDir
    try {
      & node @args2
    } finally { Pop-Location }
    Self-Clean
    exit $LASTEXITCODE
  }
  if (-not (Test-Path $NodeExe)) {
    Bad 'Node.js 环境缺失（nodejs\node.exe），请重新运行本文件'
    Read-Host '  按回车退出'
    Self-Clean
    exit 1
  }
  $env:PATH = $NodeDir + ';' + $env:PATH
  Push-Location $projDir
  try {
    & $NodeExe @args2
  } finally { Pop-Location }
  Self-Clean
  exit $LASTEXITCODE
}

# ---------- first install ----------
function Install($cfg) {
  H1 'Z80Z-chat 安装'
  Ln ''
  Info '首次运行项目安装，正在初始化项目...'
  Ln ''
  $pn = (Read-Host '  项目文件夹名称（名称后自动追加版本号，留空默认 z80z-chat-版本号）').Trim()
  if ($pn -eq '') { $pn = 'z80z-chat' }
  # 名称后自动追加版本号（已以 -版本号 结尾则不重复追加）
  if ($pn -notlike ('*-' + $AppVersion)) { $pn = $pn + '-' + $AppVersion }
  # 非法字符校验（Windows 目录名不允许 < > : " / \ | ? * 与空白）
  while ($pn -match '[<>:"/\\|?*]' -or $pn -match '\s') {
    Bad '文件夹名称包含非法字符（< > : " / \ | ? * 或空格），请重新输入'
    $pn = (Read-Host '  项目文件夹名称（名称后自动追加版本号，留空默认 z80z-chat-版本号）').Trim()
    if ($pn -eq '') { $pn = 'z80z-chat' }
    if ($pn -notlike ('*-' + $AppVersion)) { $pn = $pn + '-' + $AppVersion }
  }
  $projDir = Join-Path $Root $pn
  # 防护：目标目录已存在且非空时确认（防止覆盖已有内容/重复安装）
  if (Test-Path $projDir) {
    $nonEmpty = @(Get-ChildItem $projDir -Force -ErrorAction SilentlyContinue | Measure-Object).Count -gt 0
    if ($nonEmpty) {
      Ln ''
      Warn ('目标文件夹已存在且非空：' + $pn)
      Hint '继续安装将释放/覆盖其中的文件'
      Ln ''
      Separator
      Ln ''
      $ok = (Read-Host '  确认继续？(Y/N)').Trim()
      if ($ok -ne 'Y' -and $ok -ne 'y') {
        Ln ''
        Info '已取消安装'
        Ln ''
        Read-Host '  按回车退出'
        Self-Clean
        exit 0
      }
    }
  }

  while (-not $script:useSystemNode -and -not (Test-Path $NodeExe)) {
    if (-not (Ensure-NodeJs $cfg)) { continue }
  }

  if ($script:selLine -eq $null -and $cfg['npmRegistry'] -eq '') {
    $script:selLine = Choose-Line ('Z80Z-chat 项目依赖包（npm install，约 90MB）')
  }
  if ($script:selLine -ne $null) {
    $cfg['nodeMirror'] = $script:selLine['node']
    $cfg['npmRegistry'] = $script:selLine['npm']
  }

  New-Item -ItemType Directory -Path $projDir -Force | Out-Null
  Ln ''
  Progress '释放项目文件...'
  Write-Project $projDir
  Ask-Port $projDir
  # 镜像线路写入项目 config.json（此后配置跟随项目，不再需要外层文件）
  if ($script:selLine -ne $null) {
    Set-ConfigField $projDir 'nodeMirror' $script:selLine['node']
    Set-ConfigField $projDir 'npmRegistry' $script:selLine['npm']
  }
  Ln ''
  Invoke-NpmInstall $projDir $cfg
  Ln ''
  Invoke-NpmBuild $projDir
  Write-VersionMarker $projDir
  Remove-Item $ConfigFile -Force -ErrorAction SilentlyContinue
  $null = Set-BatPreferenceSafe 'LAST_PROJECT' $pn
  Ln ''
  Separator
  Ln ''
  Ok '安装完成'
  Ln ''
  KeyValue '项目目录' $projDir
  KeyValue '版本' $AppVersion
  Ln ''
  Hint '以后双击本文件即可进入管理菜单'
  Ln ''
  Separator
  Ln ''
  Read-Host '  按回车进入管理菜单'
  Run $projDir
}

# ---------- update tail (shared by fast / full paths): rename folder + completion screen ----------
function Finish-Update($projDir) {
  # 更新完成后同步文件夹名（名称-版本尾缀跟随新版本；失败不影响更新结果）
  # 判断依据：文件夹名自身的 -x.y.z 尾缀（不依赖 .install-version 标记版本，
  # 兼容"文件夹名版本早于标记版本"的历史错位场景）
  $oldName = Split-Path $projDir -Leaf
  $newName = ''
  if ($oldName -match '^(.*)-(\d+\.\d+\.\d+)$') {
    $newName = $Matches[1] + '-' + $AppVersion
  }
  if ($newName -ne '' -and $newName -ne $oldName) {
    if (Test-Path (Join-Path $Root $newName)) {
      Ln ''
      Warn ('目标文件夹名已存在，保持原名：' + $oldName)
    } else {
      try {
        Rename-Item $projDir $newName
        $projDir = Join-Path $Root $newName
        $null = Set-BatPreferenceSafe 'LAST_PROJECT' $newName
        Ln ''
        Ok ('项目文件夹已同步为：' + $newName)
      } catch {
        Ln ''
        Warn ('文件夹重命名失败（可能被占用），保持原名：' + $oldName)
        Hint '不影响更新结果'
      }
    }
  } else {
    $null = Set-BatPreferenceSafe 'LAST_PROJECT' $oldName
  }
  Remove-Item $ConfigFile -Force -ErrorAction SilentlyContinue
  Ln ''
  Separator
  Ln ''
  Ok '更新完成'
  Ln ''
  KeyValue '项目目录' $projDir
  KeyValue '版本' $AppVersion
  Ln ''
  Hint '以后双击本文件即可进入管理菜单'
  Ln ''
  Separator
  Ln ''
  Read-Host '  按回车进入管理菜单'
  Run $projDir
}

# ---------- update flow (decision page: update / switch version / skip prompt) ----------
function Update($cfg, $projDir, $oldVer) {
  # 与 Run 一致：本地 nodejs 缺失时回退系统 node（首次安装选择过系统 node 的场景）
  if (-not $script:useSystemNode -and -not (Test-Path $NodeExe)) {
    $sys = Test-SystemNode
    if ($sys['ok']) { $script:useSystemNode = $true }
  }
  # 已是最新版本时不再询问 Y/N，但仍保留精简界面（切版本/进管理/恢复提示入口）
  $isLatest = ($oldVer -eq $AppVersion)
  $skip = $script:globalPrefs['skipUpdatePrompt']
  # 当前版本发布时间 = 项目安装标记的 installedAt；最新版本发布时间 = 本 bat 构建时间
  $oldInstalledAt = ''
  $mkFile = Join-Path $projDir '.install-version'
  try {
    $mk = ConvertFrom-JsonCompat ([System.IO.File]::ReadAllText($mkFile, [System.Text.Encoding]::UTF8))
    $oldInstalledAt = [string](Get-JsonValue $mk 'installedAt')
  } catch {}
  H1 'Z80Z-chat 更新'
  Ln ''
  if ($isLatest) { Info '当前已是最新版本' } else { Info '检测到新版本！' }
  Ln ''
  Ln ('  当前版本：' + $oldVer + '，发布时间：' + $(if ($oldInstalledAt -eq '') { '未知' } else { $oldInstalledAt }))
  Ln ('  最新版本：' + $AppVersion + '，发布时间：' + $(if ($AppBuilt -eq '') { '未知' } else { $AppBuilt }))
  Ln ''
  Separator
  Ln ''

  if ($skip -or $isLatest) {
    # 精简界面：已设置"不再提示"或已是最新版本时不再询问 Y/N
    if ($skip) { if ($script:globalPrefs['skipUpdatePromptVersion'] -eq '') { Hint '已设置不再提示更新' } else { Hint ('已设置不再提示更新（' + $script:globalPrefs['skipUpdatePromptVersion'] + '）') } }
    Ln ''
    ItemWithDesc 1 '切换到其他版本' '在已安装的版本之间选择'
    ItemWithDesc 2 '进入当前项目管理' '不更新，直接使用当前版本'
    if ($skip) { ItemWithDesc 3 '恢复更新提示' '下次检测到新版本时重新询问' }
    Ln ''
    Separator
    Ln ''
    $ch = (Read-Host '  输入选项编号（1-3）').Trim()
    if ($ch -eq '1') { Switch-Version $cfg $projDir; return }
    if ($ch -eq '3' -and $skip) {
      $null = Set-BatPreferenceSafe 'SKIP_UPDATE_PROMPT' 'false'
      $null = Set-BatPreferenceSafe 'SKIP_UPDATE_PROMPT_VERSION' ''
      Ln ''
      Ok '已恢复更新提示'
      Ln ''
      Read-Host '  按回车继续'
      Ln ''
    }
    Run $projDir
    return
  }

  Hint '更新会进行以下步骤：'
  Hint '  · 停止当前服务'
  Hint '  · 备份数据到 data-backup/'
  Hint '  · 重建项目文件（保留 data / logs / node_modules / config.json）'
  Hint '  · 重新安装依赖并构建'
  Ln ''
  Separator
  Ln ''
  Ln ''
  $ch = (Read-Host '  确认更新？Y=更新  N=切换版本  S=不再提示更新  其他=进入管理菜单').Trim()
  if ($ch -eq 'Y' -or $ch -eq 'y') {
    Ln ''
    Stop-Service $projDir

    # ---- 智能快速更新检测：内容指纹一致且依赖未变 → 跳过备份/npm install/构建 ----
    $fast = $false
    $newHash = ''
    $fastReason = ''
    if ($PayloadSha -eq '') {
      $fastReason = '当前启动器未记录内容指纹，走完整更新'
    } elseif ($oldVer -eq '') {
      $fastReason = '目标项目无版本标记，走完整更新'
    } else {
      Progress '检查更新内容（内容指纹比对）...'
      $tmp = Join-Path $Root ('.payload-check-' + [System.Guid]::NewGuid().ToString('N'))
      New-Item -ItemType Directory -Path $tmp -Force | Out-Null
      try {
        $b64 = Extract-Block '__NODECHAT_ZIP_B64_BEGIN__' '__NODECHAT_ZIP_B64_END__'
        $tmpZip = Join-Path $tmp 'p.zip'
        [System.IO.File]::WriteAllBytes($tmpZip, [System.Convert]::FromBase64String(($b64 -join '')))
        # 解压到子目录：避免 zip 自身混入指纹计算（p.zip 会改变文件列表）
        $tmpX = Join-Path $tmp 'x'
        New-Item -ItemType Directory -Path $tmpX -Force | Out-Null
        Expand-Zip $tmpZip $tmpX
        $zipSha = Compute-PayloadSha $tmpX
        $zipDeps = Get-DepsKey (Join-Path $tmpX 'package.json')
        $oldMarker = @{}
        try { $oldMarker = ConvertFrom-JsonCompat ([System.IO.File]::ReadAllText($mkFile, [System.Text.Encoding]::UTF8)) } catch {}
        $oldHash = [string](Get-JsonValue $oldMarker 'payloadHash')
        $oldDeps = ''
        try { $oldDeps = Get-DepsKey (Join-Path $projDir 'package.json') } catch {}
        if ($zipSha -ne $PayloadSha) { $fastReason = '源码内容已更新，走完整更新' }
        elseif ($oldHash -eq '') { $fastReason = '旧版本未记录内容指纹，首次需完整更新' }
        elseif ($oldHash -ne $zipSha) { $fastReason = '旧版本代码与此版本不同，走完整更新' }
        elseif ($zipDeps -eq '' -or $zipDeps -ne $oldDeps) { $fastReason = '依赖已变化，走完整更新' }
        elseif (-not (Test-Path (Join-Path $projDir 'node_modules')) -or -not (Test-Path (Join-Path $projDir 'dist'))) { $fastReason = '依赖或构建产物缺失，走完整更新' }
        else { $fast = $true; $newHash = $zipSha }
      } catch {
        $fastReason = '更新内容检查失败（' + $_.Exception.Message + '），走完整更新'
      } finally {
        Remove-Item $tmp -Recurse -Force -ErrorAction SilentlyContinue
      }
    }

    if ($fast) {
      Ln ''
      Info '内容指纹一致，执行快速更新（无需重新下载依赖与构建，秒完成）'
      Ln ''
      Rebuild-Project $projDir
      Ln ''
      Progress '释放新版本项目文件...'
      Write-Project $projDir $true
      Write-VersionMarker $projDir $newHash
      Finish-Update $projDir
      return
    }
    if ($fastReason -ne '') {
      Ln ''
      Hint ('快速更新不可用：' + $fastReason)
      Ln ''
    }
    Backup-Data $projDir $cfg
    Rebuild-Project $projDir
    Ln ''
    Progress '释放新版本项目文件...'
    Write-Project $projDir $true
    Ln ''
    Invoke-NpmInstall $projDir $cfg
    Ln ''
    Invoke-NpmBuild $projDir
    Write-VersionMarker $projDir $PayloadSha
    Finish-Update $projDir
    return
  }
  if ($ch -eq 'S' -or $ch -eq 's') {
    $null = Set-BatPreferenceSafe 'SKIP_UPDATE_PROMPT' 'true'
    $null = Set-BatPreferenceSafe 'SKIP_UPDATE_PROMPT_VERSION' $AppVersion
    Ln ''
    Ok ('已设置不再提示更新（' + $AppVersion + '）')
    Ln ''
    Separator
    Ln ''
    Read-Host '  按回车进入管理菜单'
    Run $projDir
    return
  }
  if ($ch -eq 'N' -or $ch -eq 'n') {
    Ln ''
    Switch-Version $cfg $projDir
    return
  }
  Ln ''
  Info '已取消更新，直接进入管理菜单'
  Ln ''
  Read-Host '  按回车继续'
  Run $projDir
}

# ---------- switch between installed versions ----------
function Switch-Version($cfg, $projDir) {
  $allProjects = @(Find-Project | Sort-Object Name)
  if ($allProjects.Count -eq 0) {
    Bad '未找到已安装的项目'
    Read-Host '  按回车返回'
    Run $projDir
    return
  }
  H1 '版本选择'
  Ln ''
  Info '请选择要使用的版本：'
  Ln ''
  for ($i = 0; $i -lt $allProjects.Count; $i++) {
    $markerFile = Join-Path $allProjects[$i].FullName '.install-version'
    $ver = ''
    $installedAt = ''
    try {
      $mk = ConvertFrom-JsonCompat ([System.IO.File]::ReadAllText($markerFile, [System.Text.Encoding]::UTF8))
      $ver = Get-JsonValue $mk 'version'
      $installedAt = Get-JsonValue $mk 'installedAt'
    } catch {}
    $isCurrent = ($allProjects[$i].FullName -eq $projDir)
    $mark = ''
    if ($isCurrent) { $mark = '  [当前]' }
    if ($installedAt -ne '') { $installedAt = '  安装于 ' + $installedAt }
    Item ($i + 1) ($allProjects[$i].Name + $mark)
    Hint ('      ' + $ver + $installedAt)
  }
  Ln ''
  Separator
  Ln ''
  $ch = (Read-Host '  选择版本编号（0 返回）').Trim()
  if ($ch -eq '0') {
    Ln ''
    Info '已返回，进入当前项目管理'
    Ln ''
    Separator
    Ln ''
    Read-Host '  按回车进入管理菜单'
    Run $projDir
    return
  }
  $n = 0
  try { $n = [int]$ch } catch { $n = 0 }
  if ($n -lt 1 -or $n -gt $allProjects.Count) {
    Ln ''
    Warn '无效的编号，已返回当前项目管理'
    Ln ''
    Separator
    Ln ''
    Read-Host '  按回车返回'
    Run $projDir
    return
  }
  $targetDir = $allProjects[$n - 1].FullName
  $targetName = $allProjects[$n - 1].Name
  if ($targetDir -eq $projDir) {
    Ln ''
    Info '已在使用该版本，进入管理菜单'
    Ln ''
    Separator
    Ln ''
    Read-Host '  按回车继续'
    Run $projDir
    return
  }
  Ln ''
  Ok ('已切换到：' + $targetName)
  Ln ''
  # 记录为默认使用项目（下次双击自动进入该版本）
  $null = Set-BatPreferenceSafe 'LAST_PROJECT' $targetName
  Separator
  Ln ''
  Read-Host '  按回车进入管理菜单'
  Run $targetDir
}

# ---------- discover installed project (start.js + .install-version) ----------
function Find-Project {
  return @(Get-ChildItem $Root -Directory -ErrorAction SilentlyContinue | Where-Object {
    (Test-Path (Join-Path $_.FullName 'start.js')) -and (Test-Path (Join-Path $_.FullName '.install-version'))
  })
}

# ---------- suspect dirs: project files present but no install marker ----------
function Find-SuspectDirs {
  return @(Get-ChildItem $Root -Directory -ErrorAction SilentlyContinue | Where-Object {
    (Test-Path (Join-Path $_.FullName 'start.js')) -and -not (Test-Path (Join-Path $_.FullName '.install-version'))
  })
}

# ---------- Windows 8.1 及以下回退 Node 18 LTS ----------
function Apply-OsFallback($cfg) {
  if ([Environment]::OSVersion.Platform -eq [System.PlatformID]::Win32NT -and [Environment]::OSVersion.Version.Major -lt 10) {
    if ($cfg['nodeVersion'] -eq '22') { $cfg['nodeVersion'] = '18' }
  }
  return $cfg
}

# ---------- main ----------
try {
  $cfg = Apply-OsFallback (Read-Config)
  $found = Find-Project

  if ($found.Count -eq 0) {
    # 防护：存在含项目文件但无安装标记的目录（源码目录/未完成安装）时警告
    $suspects = Find-SuspectDirs
    if ($suspects.Count -gt 0) {
      H1 '检测到未安装的项目目录'
      Ln ''
      Warn '注意'
      Ln ''
      Hint '以下目录包含项目文件（start.js），但没有安装标记。'
      Hint '意味着这些可能是未完成安装的目录、或开发源码目录：'
      Ln ''
      foreach ($s in $suspects) {
        $count = @(Get-ChildItem $s.FullName -Force -ErrorAction SilentlyContinue | Measure-Object).Count
        Ln ('    · ' + $s.Name.PadRight(20) + '（文件数：' + $count + '）')
      }
      Ln ''
      Separator
      Ln ''
      ItemWithDesc 1 '继续安装' '在当前文件夹新建/覆盖项目'
      ItemWithDesc 2 '不安装，直接使用现有目录' '直接进入项目管理'
      ItemWithDesc 3 '退出' '稍后手动操作'
      Ln ''
      Separator
      Ln ''
      $ch = (Read-Host '  输入选项编号').Trim()
      if ($ch -eq '2') {
        $sel = $suspects[0]
        if ($suspects.Count -gt 1) {
          Ln ''
          H1 '请选择要使用的目录'
          Ln ''
          for ($i = 0; $i -lt $suspects.Count; $i++) {
            Item ($i + 1) $suspects[$i].Name
          }
          Ln ''
          Separator
          Ln ''
          $ch2 = (Read-Host '  选择要使用的目录编号').Trim()
          $n2 = 0
          try { $n2 = [int]$ch2 } catch { $n2 = 0 }
          if ($n2 -ge 1 -and $n2 -le $suspects.Count) { $sel = $suspects[$n2 - 1] }
        }
        Ln ''
        Ok ('直接使用目录：' + $sel.Name + '（不复制任何文件）')
        Ln ''
        Read-Host '  按回车继续'
        Run $sel.FullName $true
      } elseif ($ch -eq '3') {
        Ln ''
        Info '已取消，退出'
        Ln ''
        Read-Host '  按回车退出'
        Self-Clean
        exit 0
      }
      Ln ''
    }
    Install $cfg
  } else {
    $projDir = $found[0].FullName
    $resolved = $false
    if ($found.Count -gt 1) {
      # 优先使用 bat 内记录的 lastProject（上次使用/切换的项目）
      if (-not $resolved -and $script:globalPrefs['lastProject'] -ne '') {
        $m = $found | Where-Object { $_.Name -eq $script:globalPrefs['lastProject'] } | Select-Object -First 1
        if ($m) { $projDir = $m.FullName; $resolved = $true }
      }
      # 旧版外层配置记录的 projectName 优先匹配
      if (-not $resolved) {
        $legacyName = ''
        if (Test-Path $ConfigFile) {
          try {
            $lc = ConvertFrom-JsonCompat ([System.IO.File]::ReadAllText($ConfigFile, [System.Text.Encoding]::UTF8))
            $legacyName = [string](Get-JsonValue $lc 'projectName')
          } catch {}
        }
        if ($legacyName -ne '') {
          $m = $found | Where-Object { $_.Name -eq $legacyName } | Select-Object -First 1
          if ($m) { $projDir = $m.FullName; $resolved = $true }
        }
      }
      if (-not $resolved) {
        H1 '发现多个已安装项目'
        Ln ''
        Info '请选择要运行的项目：'
        Ln ''
        for ($i = 0; $i -lt $found.Count; $i++) {
          Item ($i + 1) $found[$i].Name
          $markerFile = Join-Path $found[$i].FullName '.install-version'
          $ver = ''
          try {
            $mk = ConvertFrom-JsonCompat ([System.IO.File]::ReadAllText($markerFile, [System.Text.Encoding]::UTF8))
            $ver = Get-JsonValue $mk 'version'
          } catch {}
          if ($ver -ne '') {
            Tone '38;5;244' ('      版本：' + $ver)
          }
        }
        Ln ''
        Separator
        Ln ''
        $ch = (Read-Host '  选择项目编号').Trim()
        $n = 0
        try { $n = [int]$ch } catch { $n = 0 }
        if ($n -ge 1 -and $n -le $found.Count) {
          $projDir = $found[$n - 1].FullName
          $null = Set-BatPreferenceSafe 'LAST_PROJECT' $found[$n - 1].Name
        }
      }
    }
    $cfg = Apply-OsFallback (Read-Config $projDir)
    $markerFile = Join-Path $projDir '.install-version'
    $oldVer = ''
    try {
      $mk = ConvertFrom-JsonCompat ([System.IO.File]::ReadAllText($markerFile, [System.Text.Encoding]::UTF8))
      $oldVer = Get-JsonValue $mk 'version'
    } catch {}
    if ($oldVer -eq $AppVersion -and -not $script:globalPrefs['skipUpdatePrompt'] -and $found.Count -eq 1) {
      Run $projDir
    } else {
      Update $cfg $projDir $oldVer
    }
  }
} catch {
  H1 '错误'
  Ln ''
  Bad ('错误：' + $_.Exception.Message)
  Ln ''
  Separator
  Ln ''
  Info '错误详情：'
  Ln ''
  Hint ($_.ScriptStackTrace)
  Ln ''
  Separator
  Ln ''
  Read-Host '  按回车退出'
  Self-Clean
  exit 1
}
__NODECHAT_PS_END__
__NODECHAT_PS_B64_BEGIN__
__PS_B64_PLACEHOLDER__
__NODECHAT_PS_B64_END__
__NODECHAT_STARTJS_BEGIN__
__STARTJS_PLACEHOLDER__
__NODECHAT_STARTJS_END__
__NODECHAT_ZIP_B64_BEGIN__
__ZIP_B64_PLACEHOLDER__
__NODECHAT_ZIP_B64_END__

:RUN
powershell -NoProfile -ExecutionPolicy Bypass -Command "$l=[IO.File]::ReadAllLines('%~f0',[Text.Encoding]::UTF8);$s=[Array]::IndexOf($l,'__NODECHAT_PS_B64_BEGIN__');$e=[Array]::IndexOf($l,'__NODECHAT_PS_B64_END__');if($s -lt 0 -or $e -lt 0){exit 9};$b=[Convert]::FromBase64String(($l[($s+1)..($e-1)] -join ''));[IO.File]::WriteAllBytes('%~dp0.z80z-chat-bootstrap.ps1',$b)" <nul
if not exist "%BS%" goto :FAIL
goto :MAIN

:FAIL
echo [Z80Z-chat] bootstrap extraction failed. The file may be corrupted.
pause
exit /b 9

REM The bootstrap PS must be the LAST command in this file: it
REM rewrites this bat in place (preferences), and cmd reads the
REM file sequentially - any content after this line would be
REM misaligned and executed as garbage ('" is not recognized',
REM exit code 9009). Jumping to :MAIN keeps the PS line as the
REM final command; cmd reads EOF right after it.
:MAIN
powershell -NoProfile -ExecutionPolicy Bypass -File "%BS%" -Root "%~dp0." -AppVersion "%APP_VERSION%" -AppBuilt "%APP_BUILT%" -SkipUpdatePrompt "%SKIP_UPDATE_PROMPT%" -SkipUpdatePromptVersion "%SKIP_UPDATE_PROMPT_VERSION%" -LastProject "%LAST_PROJECT%" -PayloadSha "%PAYLOAD_SHA%"